github_poll_interval: 120         # seconds
webhook_poll_interval: 5          # seconds
webhook_base_url: "https://webhook.c2coder.eu" 

repositories:
  - name: Robutek
    path: "repo/Robutek"
    repo: "C2Coder/Robutek"
    branch: "gh-pages"
    update_method: "webhook"      # options: "github", "webhook", "both"
    host_http_server: true
    domain: "robutek.robotikabrno.cz"
    http_port: 8081               # ports must be unique across all repositories
  
  - name: RoboCamp-2025
    path: "repo/RoboCamp-2025"
    repo: "RoboticsBrno/RoboCamp-2025"
    branch: "gh-pages"
    update_method: "github"       # options: "github", "webhook", "both"
    host_http_server: true
    domain: "2025.robotickytabor.cz"
    http_port: 8082               # ports must be unique across all repositories
