github_poll_interval: 60         # seconds
webhook_poll_interval: 10        # seconds
webhook_base_url: "https://webhook.c2coder.eu"

repositories:
  - name: Robutek
    path: "./repo/Robutek"
    repo: "C2Coder/Robutek"
    branch: "gh-pages"
    update_method: "webhook"       # options: "github", "webhook", "both"
    host_http_server: true
    http_port: 8081
  
  - name: RoboCamp-2025
    path: "./repo/RoboCamp-2025"
    repo: "RoboticsBrno/RoboCamp-2025"
    branch: "gh-pages"
    update_method: "github"       # options: "github", "webhook", "both"
    host_http_server: true
    http_port: 8082
