listen: 0.0.0.0   # bind address
port: 53          # UDP port (needs root or CAP_NET_BIND_SERVICE <1024)

upstream_dns: 1.1.1.1

# TTL for all synthesized records (seconds)
ttl: 300

# Domain to return in A answers for banned domains
banned_ip: 127.0.0.1 # redirect to localhost on their machines

# Path to the text file containing banned domains
banned_list:
  - ./dns/banned.txt 
  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/nsfw-onlydomains.txt

# How to match banned domains: "exact" | "suffix" (suffix matches subdomains)
banned_mode: suffix

# If you want to override auto-detected local IP, set it here; otherwise omit or set null
server_ip: null

# Static records
records:
  A:
    files.lan: server
    vps.c2coder.eu: "89.168.102.205"
    webhook.c2coder.eu: "89.168.102.205"
    robutek.robotikabrno.cz: server
    robocoin.robotikabrno.cz: server
    2024.robotickytabor.cz: server
    gadgets.robotikabrno.cz: server
    smd-challenge.robotikabrno.cz: server
  CNAME:
    robutek.lan: robutek.robotikabrno.cz
    robocoin.lan: robocoin.robotikabrno.cz
    navod.lan: 2024.robotickytabor.cz
    gadgets.lan: gadgets.robotikabrno.cz
    smd-challenge.lan: smd-challenge.robotikabrno.cz